definitions:
  api.FileUploadResponse:
    properties:
      cid:
        type: string
    type: object
info:
  contact: {}
  description: A secure, decentralized file sharing platform with end-to-end encryption,
    digital signatures, temporary links, and blockchain audit trails.
  title: SafeTransfer API
  version: "1.0"
paths:
  /upload:
    post:
      consumes:
      - application/json
      description: Uploads a file to IPFS and returns the CID.
      parameters:
      - description: File to upload
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.FileUploadResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Uploads a file to IPFS
      tags:
      - File
swagger: "2.0"
